### ISSUE TITLE
Error when connect to Server Socket

### ISSUE THREAD

**Issue by luzadev** [ComfortablyCoding/strapi-plugin-io#28]
Hi,
when I try to connect to Server Socket STRAPI v4 I get this error:
Server Strapi: http://localhost:1337

```
------------------
Error: server.handleUpgrade() was called more than once with the same socket, possibly due to a misconfiguration
    at WebSocketServer.completeUpgrade (/Users/luciano/Sviluppo/Sites/Sugar/backend/node_modules/ws/lib/websocket-server.js:340:13)
    at WebSocketServer.handleUpgrade (/Users/luciano/Sviluppo/Sites/Sugar/backend/node_modules/ws/lib/websocket-server.js:316:10)
    at /Users/luciano/Sviluppo/Sites/Sugar/backend/node_modules/engine.io/build/server.js:397:21
    at Server.verify (/Users/luciano/Sviluppo/Sites/Sugar/backend/node_modules/engine.io/build/server.js:127:24)
    at Server.handleUpgrade (/Users/luciano/Sviluppo/Sites/Sugar/backend/node_modules/engine.io/build/server.js:383:14)
    at Server.<anonymous> (/Users/luciano/Sviluppo/Sites/Sugar/backend/node_modules/engine.io/build/server.js:495:26)
    at Server.emit (events.js:412:35)
    at Server.emit (domain.js:475:12)
    at onParserExecuteCommon (_http_server.js:703:14)
    at onParserExecute (_http_server.js:616:3)
    at HTTPParser.callbackTrampoline (internal/async_hooks.js:130:17)
[2022-06-16 14:40:18.246] info: [io] new connection with id ZfjjKoUIkus04BQfAAAB
-------------------
```

My Configuration is:

```
module.exports = ({env}) => {
  return ({
    io: {
     enabled: true,
     config: {
      IOServerOptions :{
        cors: { "origin": "http://localhost:3000", "methods": ["GET"] },
      },
      contentTypes: {
        "message": "*",
      },
      events:[
         {
           "name": "connection",
           "handler": ({ strapi }, socket) => {
             //strapi.$io.raw('test', 'CIAO');
             strapi.log.info(`[io] new connection with id ${socket.id}`);
             strapi.log.info(`[io] Transport ${socket.conn.transport.name}`);
           },
         },
       ]
     },
   },
{...}

```
Client Connection:

```
const SERVER_URL = "http://localhost:1337";
const JWT_TOKEN = "xxxxxxxxxxxxx";
const socket = io(SERVER_URL, {
    auth: {
        token: JWT_TOKEN
    },
});

useEffect(() => {
        console.log('CONNECTION....')
        socket.on("connect", () => {
            console.log(socket.id);
            socket.on("message", (data: any) => {
                console.log(data)
            });
        })
    });

```
How can I resolve the issue?

Thanks

**Comment by ComfortablyCoding** [comment]
I would say it's due to your useEffect hook and not the library.

It looks like it is being called multiple times (each render) and causing this issue. Limitting useEffect to be called only once per connection should resolve the issue.
