### ISSUE TITLE
[Bug]: getting error 

### ISSUE THREAD

**Issue by tolgig** [ComfortablyCoding/strapi-plugin-io#68]
### What issue are you experiencing?

hi,
i following the guide to install the plugin.
https://strapi-plugin-io.netlify.app/guide/getting-started.html
Step 1 : yarn add strapi-plugin-io
Step 2: Add configutation to the config.js

but getting following error after starting strapi.
`[2023-11-28 13:02:57.662] debug: ⛔️ Server wasn't able to start properly.
[2023-11-28 13:02:57.663] error: Error regarding io config: [
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "object",
    "path": [
      "events"
    ],
    "message": "Expected array, received object"
  }
]
Error: Error regarding io config: [
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "object",
    "path": [
      "events"
    ],
    "message": "Expected array, received object"
  }
]
    at applyUserConfig (/Users/tolgagigel/Code/rubicoda/Succuba/api/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:72:13)
    at async Object.loadPlugins (/Users/tolgagigel/Code/rubicoda/Succuba/api/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:100:3)
    at async Strapi.loadPlugins (/Users/tolgagigel/Code/rubicoda/Succuba/api/node_modules/@strapi/strapi/lib/Strapi.js:336:5)
    at async Promise.all (index 2)
    at async Strapi.register (/Users/tolgagigel/Code/rubicoda/Succuba/api/node_modules/@strapi/strapi/lib/Strapi.js:372:5)
    at async Strapi.load (/Users/tolgagigel/Code/rubicoda/Succuba/api/node_modules/@strapi/strapi/lib/Strapi.js:477:5)
    at async Strapi.start (/Users/tolgagigel/Code/rubicoda/Succuba/api/node_modules/@strapi/strapi/lib/Strapi.js:212:9)
error Command failed with exit code 1.`

any ideas?

### Steps To Reproduce

1. node v18.17.1
2. strapi version 4.5.4
3. yarn add strapi-plugin-io
4. Add to config.ts

`  io: {
		enabled: true,
		config: {
			// This will listen for all supported events on the article content type
			contentTypes: ['api::article.article'],
		},
	},`

### What version of the plugin are you using?

latest

### What strapi version are you using?

4.5.4

**Comment by ComfortablyCoding** [comment]
Thanks for the report, this should be fixed in v2.0.3. Please re-install that version and let me know if this issue still pops up.

**Comment by tolgig** [comment]
hi @ComfortablyCoding . yes, everything works now. Thanks for this fast fix!
