### ISSUE TITLE
Strategy `apiToken` authentication error

### ISSUE THREAD

**Issue by joaquinodz** [ComfortablyCoding/strapi-plugin-io#78]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `strapi-plugin-io@2.0.4` for the project I'm working on.

When you try to authenticate using the `apiToken` strategy, you get the following error:
```
Error: select "t0"."id", "t0"."name", "t0"."type", "t0"."expires_at", "t0"."last_used_at" from "public"."strapi_api_tokens" as "t0" where ("t0"."id" = $1) limit $2 - invalid input syntax for type integer: "<token>"
    at Socket.onpacket (D:\dev\contact-center-socket-client\node_modules\socket.io-client\build\cjs\socket.js:485:29)
    at Emitter.emit (D:\dev\contact-center-socket-client\node_modules\@socket.io\component-emitter\index.js:143:20)
    at D:\dev\contact-center-socket-client\node_modules\socket.io-client\build\cjs\manager.js:237:18
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  data: undefined
}
```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/strapi-plugin-io/server/services/strategies.js b/node_modules/strapi-plugin-io/server/services/strategies.js
index 4bc1375..c1b482a 100644
--- a/node_modules/strapi-plugin-io/server/services/strategies.js
+++ b/node_modules/strapi-plugin-io/server/services/strategies.js
@@ -1,6 +1,7 @@
 'use strict';
 
 const { castArray, isNil, pipe, every } = require('lodash/fp');
+const { differenceInHours, parseISO } = require('date-fns');
 const { getService } = require('../utils/getService');
 const { UnauthorizedError, ForbiddenError } = require('@strapi/utils').errors;
 
@@ -101,9 +102,12 @@ module.exports = ({ strapi }) => {
 				throw new UnauthorizedError('Invalid credentials');
 			}
 
-			const apiToken = await strapi.entityService.findOne('admin::api-token', apiTokenService.hash(token), {
+			const apiToken = await strapi.entityService.findMany('admin::api-token', {
 				fields: ['id', 'name', 'lastUsedAt', 'expiresAt'],
-			});
+				filters: {
+					access_key: apiTokenService.hash(token),
+				}
+			}).then((tokens) => tokens[0]);
 
 			// token not found
 			if (!apiToken) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

Tested on Strapi v4.16.2

**Comment by ComfortablyCoding** [comment]
Thanks for the report! This should be fixed in v2.0.5
